select * from sakila.film;
select title, release_year from sakila.film;
select actor_id from sakila.actor;
select actor_id, first_name from sakila.actor;
select actor_id, first_name, last_name from sakila.actor;
Select actor_id, first_name, last_name, last_update from sakila.actor;
select * from sakila.actor;
select address_id from sakila.address;
select address_id, address from sakila.address;
select address_id, address, address2 from sakila.address;
select address_id, address, address2, district from sakila.address;
select address_id, address, address2, district, city_id from sakila.address;
select address_id, address, address2, district, city_id, postal_code from sakila.address;
select address_id, address, address2, district, city_id, postal_code, phone from sakila.address;
select address_id, address, address2, district, city_id, postal_code, phone, location from sakila.address;
select address_id, address, address2, district, city_id, postal_code, phone, location, last_update from sakila.address;
select * from sakila.address;
select category_id from sakila.category;
select category_id, name from sakila.category;
select category_id, name, last_update from sakila.category;
select * from sakila.category;
select city_id from sakila.city;
select city_id, city from sakila.city;
select city_id, city, country_id from sakila.city;
select city_id, city, country_id, last_update from sakila.city;
select * from sakila.city;
select country_id from sakila.country;
select country_id, country from sakila.country;
select country_id, country, last_update from sakila.country;
select * from sakila.country;
select customer_id from sakila.customer;
select customer_id, store_id from sakila.customer;
select customer_id, store_id, first_name from sakila.customer;
select customer_id, store_id, first_name, last_name from sakila.customer;
select customer_id, store_id, first_name, last_name, email from sakila.customer;
select customer_id, store_id, first_name, last_name, email, address_id from sakila.customer;
select customer_id, store_id, first_name, last_name, email, address_id, active from sakila.customer;
select customer_id, store_id, first_name, last_name, email, address_id, active, create_date from sakila.customer;
select customer_id, store_id, first_name, last_name, email, address_id, active, create_date, last_update from sakila.customer;
select * from sakila.customer;
select film_id from sakila.film;
select film_id, title from sakila.film;
select film_id, title, description from sakila.film;
select film_id, title, description, release_year from sakila.film;
select film_id, title, description, release_year, language_id from sakila.film;
select film_id, title, description, release_year, language_id, original_language_id from sakila.film;
select film_id, title, description, release_year, language_id, original_language_id, rental_duration from sakila.film;
select film_id, title, description, release_year, language_id, original_language_id, rental_duration, rental_rate from sakila.film;
select film_id, title, description, release_year, language_id, original_language_id, rental_duration, rental_rate, length from sakila.film;
select film_id, title, description, release_year, language_id, original_language_id, rental_duration, rental_rate, length, special_features from sakila.film;
select film_id, title, description, release_year, language_id, original_language_id, rental_duration, rental_rate, length, special_features, last_update from sakila.film;
select * from sakila.film;
select actor_id from sakila.film_actor;
select actor_id, film_id from sakila.film_actor;
select actor_id, film_id, last_update from sakila.film_actor;
select * from sakila.film_actor;
select film_id from sakila.film_category;
select film_id, category_id from sakila.film_category;
select film_id, category_id, last_update from sakila.film_category;
select * from sakila.film_category;
select film_id from sakila.film_text;
select film_id, description from sakila.film_text;
select film_id, title, description from sakila.film_text;
select * from  sakila.film_text;
select inventory_id from sakila.inventory;
select inventory_id, film_id from sakila.inventory;
select inventory_id, film_id, store_id from sakila.inventory;
select inventory_id, film_id, store_id, last_update from sakila.inventory;
select * from sakila.inventory;
select language_id from sakila.language;
select language_id, name from sakila.language;
select language_id, name, last_update from sakila.language;
select * from sakila.language;
select payment_id from sakila.payment;
select payment_id, customer_id from sakila.payment;
select payment_id, customer_id, staff_id from sakila.payment;
select payment_id, customer_id, staff_id, rental_id from sakila.payment;
select payment_id, customer_id, staff_id, rental_id, payment_date from sakila.payment;
select payment_id, customer_id, staff_id, rental_id, payment_date, last_update from sakila.payment;
select * from sakila.payment;
select rental_id from sakila.rental;
select rental_id, rental_date from sakila.rental;
select rental_id, return_date, inventory_id from sakila.rental;
select rental_id, return_date, inventory_id, customer_id from sakila.rental;
select rental_id, rental_date, inventory_id, customer_id, return_date from sakila.rental;
select rental_id, rental_date, inventory_id, customer_id, return_date, staff_id from sakila.rental;
select rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update from sakila.rental;
select * from sakila.rental;
select staff_id from sakila.staff;
select staff_id, first_name from sakila.staff;
select staff_id, first_name, last_name from sakila.staff;
select staff_id, first_name, last_name, address_id from sakila.staff;
select store_id, first_name, last_name, address_id, email from sakila.staff;
select store_id, first_name, last_name, address_id, picture, email from sakila.staff;
select store_id, first_name, last_name, address_id, picture, email, active, username, password, last_update from sakila.staff;
select * from sakila.staff;
